sudo:
  - required

services:
  - docker

deploy:
  provider: heroku
  api_key:
    secure: "fa12497b-a48c-4e94-b055-7b7a4546efd6"
  app: ess-atomic-swap
  on:
    all_branches: true

before_install:
  - docker-compose -f docker-development-compose.yml build
  - docker-compose -f docker-development-compose.yml up -d
  ## Wait start daemon
  - sleep 30
script:
  - docker exec -it ess-atomic-swap bash -c "make run_golangci_lint"
  - docker exec -it ess-atomic-swap bash -c "make run_unit_tests"
