sudo:
  - required

services:
  - docker

before_install:
  - docker-compose -f docker-development-compose.yml build
  - docker-compose -f docker-development-compose.yml up -d
  ## Wait start daemon
  - sleep 10
script:
  - docker exec -it ess-atomic-swap bash -c "golint ./..."
  - docker exec -it ess-atomic-swap bash -c "go test ./..."
