version: '3'
services:
  ess-atomic-swap:
    container_name: ess-atomic-swap
    environment:
      - PORT=${PORT}
      - DEV_PORT=${DEV_PORT}
      - DEVELOPMENT=true
      - BTC_ADDR=${BTC_ADDR}
      - ETH_ADDR=${ETH_ADDR}
      - SCDB_ADDR=${SCDB_ADDR}
      - PRIVATE_KEY="${PRIVATE_KEY}"
    build:
      context: .
      dockerfile: Dockerfile-development
    volumes:
      - .:/go/src/github.com/essentiaone/ess-atomic-swap
    ports:
      - '${PORT}:${DEV_PORT}'
