FROM golang:1.10.3
RUN mkdir -p /go/src/github.com/essentiaone/ess-atomic-swap
WORKDIR /go/src/github.com/essentiaone/ess-atomic-swap
COPY . /go/src/github.com/essentiaone/ess-atomic-swap
CMD ["go", "get", "github.com/ethereum/go-ethereum"]
CMD ["make", "run_production"]
