version: '3'
services:
  ess-atomic-swap:
    container_name: ess-atomic-swap
    environment:
      - PORT=${PORT}
      - DEV_PORT=${DEV_PORT}
      - DEVELOPMENT=false
      - BTC_ADDR=${BTC_ADDR}
      - ETH_ADDR=${ETH_ADDR}
    build:
      context: .
      dockerfile: Dockerfile-production
    volumes:
      - .:/go/src/github.com/essentiaone/ess-atomic-swap
    ports:
      - '${PORT}:${PORT}'
